RESKC-807: Fix Protocol copy.
Attempt to copy an IRB or IACUC protocol. Tested on newly created protocol and older ones.
Get:
org.kuali.rice.krad.exception.UnknownDocumentIdException: Document no longer exists. It may have been cancelled before being saved.