RESKC-560:Fix issues with adding/removing committee members from present/absentee list
Edit an IRB or IACUC schedule
In attendance:
-set a member as Present Voting
-then set the other member as Present Voting
Save
Members revert to Absent.

Sometimes a member will not even move to Present after clicking Present Voting

Mark a selected attendee as absent get:
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 at java.util.ArrayList.rangeCheck(ArrayList.java:653) at java.util.ArrayList.get(ArrayList.java:429) at org.kuali.coeus.common.committee.impl.meeting.MeetingServiceImplBase.markAbsent(MeetingServiceImplBase.java:240)....

Captured a video to show the various things going on.

Full stack trace:
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0