RESOPS-653:Copied awards with multiple award amount info errors on save
Awards copied that contain multiple award amount infos from a time and money document fail on initial save with the following error.
```
org.springframework.dao.DataIntegrityViolationException: OJB operation; SQL []; Column 'AWARD_NUMBER' cannot be null; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'AWARD_NUMBER' cannot be null
```
This was because the indexOfAwardAmountInfoToDisplay would get set during versioning/sequencing due to a lazy initializer. After the versioning the amount info list is truncated leaving the indexOfAmountInfoToDisplay at a much higher number than exists. Then the KNS view of the initial page would populate the awardAmountInfo list with new, uninitialized values. Attempting to save these new items would throw the exception above.