RESKC-589: Fixing proposal copy Tried to copy proposal (status Approved and Submitted) from search results Action link "Copy" (proposal had no subawards)
In Copy modal:
Selected same lead unit 264000
Selected:
Copy budget, final version
Copy Attachments
Copy Questionnaire.
Clicked Copy. Got error message (see screenshot) and STE below.

Tried again
All same selections but did not select to include Attachments.
Same errors & STE

STE:

Stacktrace (only in dev mode)

java.lang.RuntimeException: An error occured while trying to copy the proposal development document.
at org.kuali.coeus.propdev.impl.copy.ProposalCopyServiceImpl.copyProposal(ProposalCopyServiceImpl.java:239)
at org.kuali.coeus.propdev.impl.copy.ProposalDevelopmentCopyController.copy(ProposalDevelopmentCopyController.java:62)
Caused by: org.kuali.rice.krad.exception.ValidationException: business rule evaluation failed
at org.kuali.rice.krad.document.DocumentBase.validateBusinessRules(DocumentBase.java:521)
at org.kuali.coeus.sys.framework.model.KcTransactionalDocumentBase.validateBusinessRules(KcTransactionalDocumentBase.java:146)
at org.kuali.rice.krad.service.impl.DocumentServiceImpl.validateAndPersistDocument(DocumentServiceImpl.java:876)
at org.kuali.rice.krad.service.impl.DocumentServiceImpl.validateAndPersistDocumentAndSaveAdHocRoutingRecipients(DocumentServiceImpl.java:502)
at org.kuali.rice.krad.service.impl.DocumentServiceImpl.saveDocument(DocumentServiceImpl.java:156)